### ISSUE TITLE
2Dゲーム環境の再現

### ISSUE THREAD

**Issue by mashimashica** [mashimashica/WM2021_LWM#6]

**Comment by otanet** [comment]
# 20220322 0930時点
# pybulletについて調べ、グリッドのマップを行列データで返す前まで完了しています。

! pip install pybullet


import time
import os

import gym
import pybullet_envs  # PyBulletの環境をgymに登録する

import numpy as np
import matplotlib.pyplot as plt

import torch
from torch.distributions import Normal
from torch.distributions.kl import kl_divergence
from torch import nn
from torch.nn import functional as F
from torch.nn.utils import clip_grad_norm_
from torch.utils.tensorboard import SummaryWriter


# TensorBoardで可視化
%load_ext tensorboard! pip install pybullet

**Comment by envzhu** [comment]
参考までに
見つけるのが遅くなって申し訳ないのですが，[Learning to Ground Multi-Agent Communication with Autoencoders](https://toruowo.github.io/marl-ae-comm/)という論文がGridゲーム環境を用いたマルチエージェントの実験を行っており，実装がしかも公開されていました．
実装：[ToruOwO/marl-ae-comm: PyTorch implementation for all models and environments in the paper &quot;Learning to Ground Multi-Agent Communication with Autoencoders&quot;](https://github.com/ToruOwO/marl-ae-comm)
https://github.com/ToruOwO/marl-ae-comm/tree/main/marl-grid/find-goal　にGrid上のゴールを見つけるゲームによる実験が実装されています．
以下のライブラリが使用されているようです
- [maximecb/gym-minigrid: Minimalistic gridworld package for OpenAI Gym](https://github.com/maximecb/gym-minigrid)
- [kandouss/marlgrid: Gridworld for MARL experiments](https://github.com/kandouss/marlgrid)

**Comment by otanet** [comment]
上記、ありがとうございます。
Language World Modelsは、やはり、Multi-AgentとAutoencoderとで、画像データをやり取りするイメージでおります。
以前、深層強化学習の最終課題に、対話の強化学習を選んだのですが、この時よりも、画像データのやり取りにおけるlanguageということで、かんねんしたという感じです。
昨年の人工知能学会の世界モデルで、自然言語処よりの論文で、数理論理学のような概念的なアプローチとも違うので、上記のURLで慣れてゆきたいと思います。

- 上記が本日までの進捗になります。
- 次回以降は、理解したものを実装する流れで、予定しております。

**Comment by envzhu** [comment]
こちら早めに完了させたいです

**Comment by otanet** [comment]
現状の認識では、MarlGridで対応できると考えている。
OpenAIGym>MarlGrid
https://github.com/kandouss/marlgrid/blob/master/marlgrid/envs/cluttered.py

##
Have done.
既存のゲーム環境を調査
Pre-built environment
https://github.com/kandouss/marlgrid/blob/master/marlgrid/envs/cluttered.py
→OpenAI GymとUnityにおけるゲーム環境の位置づけを概観

##
Next Action.
要件定義: 
-色を付ける: 緑と青
-値の受け渡し
-Unityでやるか、見た目

以上

**Comment by envzhu** [comment]
こちら，無事マージされたようなのでクローズします
